project_id = "tzgztyaompezflmavptj"

[functions.analyze-symptoms]
verify_jwt = false

[functions.send-queue-notification]
verify_jwt = false

[functions.send-appointment-notification]
verify_jwt = false